class SynapseA2a < Formula
  include Language::Python::Virtualenv

  desc "Agent-to-Agent communication protocol for CLI agents"
  homepage "https://github.com/s-hiraoku/synapse-a2a"
  url "https://files.pythonhosted.org/packages/source/s/synapse-a2a/synapse_a2a-0.5.0.tar.gz"
  sha256 "PLACEHOLDER_SHA256"
  license "MIT"

  depends_on "python@3.12"

  # ==========================================================================
  # Resource stanzas below are auto-generated by homebrew-pypi-poet.
  # Run: scripts/patch_homebrew_formula.py to regenerate after version bumps.
  # ==========================================================================

  # RESOURCE_STANZAS_START
  # To generate resource stanzas:
  #   python3 -m venv /tmp/poet-env
  #   /tmp/poet-env/bin/pip install synapse-a2a homebrew-pypi-poet
  #   /tmp/poet-env/bin/poet -f synapse-a2a
  #
  # Then run: python scripts/patch_homebrew_formula.py <version>
  # RESOURCE_STANZAS_END

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/synapse --version")
  end
end
